NetworkServicesGateway/Models/ErrorViewModel.cs
namespace NetworkServicesGateway.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NetworkServicesGateway/Models/NetworkActionResult.cs
using System.Net.NetworkInformation;

namespace NetworkServicesGateway.Models
{
    public enum NetworkServiceState
    {
        Started = 1,
        Running,
        Stopped,
        StoppedByException
    }

    public class NetworkActionResult
    {
        public NetworkServiceState State { get; set; }
        public string Message { get; set; } = default!;
        public static NetworkActionResult StartedResult => new NetworkActionResult()
        {
            State = NetworkServiceState.Started
        };
        public static NetworkActionResult RunningResult => new NetworkActionResult()
        {
            State = NetworkServiceState.Running
        };
        public static NetworkActionResult StoppedResult => new NetworkActionResult()
        {
            State = NetworkServiceState.Stopped
        };
        public static NetworkActionResult StoppedByExceptionResult => new NetworkActionResult()
        {
            State = NetworkServiceState.StoppedByException
        };
    }
}

NetworkServicesGateway/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace NetworkServicesGateway.Models
{
    public class User
    {
        [Required]
        public string Name { get; set; } = default!;
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; } = default!;
    }
}

NetworkServicesGateway/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using NetworkServicesGateway.Extensions;
using NetworkServicesGateway.Models;

namespace NetworkServicesGateway.Controllers
{
    public class AuthController : Controller
    {
        [HttpGet("/auth")]
        public IActionResult Authorize()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetUserName()))
                return Redirect("/");

            return View("Login");
        }

        [HttpPost("/auth")]
        public IActionResult Authorize(User userModel)
        {
            if (ModelState.IsValid && userModel.Name == "admin" && userModel.Password == "admin")
            {
                HttpContext.Session.SetUserName(userModel.Name);
                return Redirect("/");
            }
            ModelState.AddModelError(nameof(userModel.Name), "Błędny login lub hasło");
            return View("Login", userModel);
        }
    }
}

NetworkServicesGateway/Controllers/GatewayController.cs
using Microsoft.AspNetCore.Mvc;
using NetworkServicesGateway.Extensions;
using NetworkServicesGateway.Models;

namespace NetworkServicesGateway.Controllers
{
    [Route("/")]
    public class GatewayController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetUserName()))
                return Redirect("/auth");

            return View();
        }
    }
}

NetworkServicesGateway/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NetworkServicesGateway.Models;
using System.Diagnostics;

namespace NetworkServicesGateway.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NetworkServicesGateway/Views/Gateway/Index.cshtml
@using NetworkServicesGateway.Services
@{
    var types = Enum.GetValues<NetworkServiceType>();
}

<div class="network-monitor-main">
    <label for="input-address-ip">Adres IP</label>
    <input type="text" id="input-address-ip" />

    @foreach(var t in types)
    {
        @if(t == NetworkServiceType.Ping)
        {
            <input type="radio" name="serviceType" checked id="@t.ToString()" value="@((int)t)">
             <label for="@t.ToString()">@t.ToString()</label>
        }
        else
        {
            <input type="radio" name="serviceType" id="@t.ToString()" value="@((int)t)">
            <label for="@t.ToString()">@t.ToString()</label>
        }
    }

    <button id="button-start">Start</button>
    <button id="button-stop" style="display: none;">Stop</button>
    <button id="button-clear">Wyczyść</button>

    <div id="messages-wrapper">
    </div>

</div>

NetworkServicesGateway/Views/Shared/Login.cshtml
@model NetworkServicesGateway.Models.User

@{
    ViewData["Title"] = "View";
}

<h4>Logowanie</h4>
<span>admin/admin</span>
<hr />
<div class="justify-content-center">
    <div class="row">
        <div class="col-md-4">
            <form asp-route="/auth">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>  
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Login" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

NetworkServicesGateway/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>NetworkServicesGateway</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetworkServicesGateway.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Gateway" asp-action="Index">NetworkServicesGateway</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NetworkServicesGateway 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/microsoft/signalr.js"></script>
    <script src="~/js/network-services.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>